app:
  port: 8194
  debug: True
  key: dify-sandbox
max_workers: 4
max_requests: 50
worker_timeout: 2000
python_path: /usr/local/bin/python3
enable_network: True
allowed_syscalls:
proxy:
  socks5: ''
  http: ''
  https: ''
