"""One-click FA agent install: serve collector + generated install.sh."""

from __future__ import annotations

import re
from pathlib import Path

from fastapi import APIRouter, HTTPException, Query, Request
from fastapi.responses import FileResponse, PlainTextResponse

router = APIRouter(prefix="/agent", tags=["agent"])

_COLLECTOR_PATH = (
    Path(__file__).resolve().parent.parent / "src" / "agent" / "collector.py"
)

_SERVER_ID_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$")


def _public_base(request: Request) -> str:
    return str(request.base_url).rstrip("/")


def _build_install_script(base_url: str, server_id: str) -> str:
    center_url = f"{base_url}/api/collect"
    collector_url = f"{base_url}/api/agent/collector.py"
    # Values are validated / URL-derived; still keep shell-safe quoting via single quotes
    # after escaping embedded single quotes.
    def sh_quote(value: str) -> str:
        return "'" + value.replace("'", "'\"'\"'") + "'"

    q_server = sh_quote(server_id)
    q_center = sh_quote(center_url)
    q_collector = sh_quote(collector_url)

    return f"""#!/bin/bash
# FA Diagnosis Agent — one-click installer (generated by center)
# Usage: curl -fsSL {base_url}/api/agent/install.sh?server_id=Node-01 | sudo bash
set -euo pipefail

SERVER_ID={q_server}
CENTER_URL={q_center}
COLLECTOR_URL={q_collector}

AGENT_DIR="/opt/fa-agent"
LOG_DIR="/var/log/fa-agent"
COLLECTOR_DST="${{AGENT_DIR}}/collector.py"
SERVICE_FILE="/etc/systemd/system/fa-collector.service"
TIMER_FILE="/etc/systemd/system/fa-collector.timer"
TMP_COLLECTOR="$(mktemp /tmp/fa-collector.XXXXXX.py)"

log() {{ echo "[fa-agent-install] $*"; }}
die() {{ echo "[fa-agent-install] ERROR: $*" >&2; exit 1; }}

[[ "$(id -u)" -eq 0 ]] || die "please run as root (sudo)"

# Allow override: FA_CENTER=http://x.x.x.x:8000/api/collect
if [[ -n "${{FA_CENTER:-}}" ]]; then
  CENTER_URL="$FA_CENTER"
fi

log "server-id=${{SERVER_ID}}"
log "center=${{CENTER_URL}}"
log "downloading collector from ${{COLLECTOR_URL}}"

if command -v curl >/dev/null 2>&1; then
  curl -fsSL "$COLLECTOR_URL" -o "$TMP_COLLECTOR" \\
    || die "failed to download collector.py (check center URL / firewall)"
elif command -v wget >/dev/null 2>&1; then
  wget -qO "$TMP_COLLECTOR" "$COLLECTOR_URL" \\
    || die "failed to download collector.py (check center URL / firewall)"
else
  die "need curl or wget to download collector.py"
fi

grep -q "FA hardware monitoring agent" "$TMP_COLLECTOR" \\
  || die "downloaded file does not look like collector.py"

detect_pkg_mgr() {{
  if command -v apt-get >/dev/null 2>&1; then echo apt
  elif command -v yum >/dev/null 2>&1; then echo yum
  elif command -v dnf >/dev/null 2>&1; then echo dnf
  else echo ""; fi
}}
PKG_MGR="$(detect_pkg_mgr)"

ensure_python() {{
  if command -v python3 >/dev/null 2>&1; then
    python3 -c 'import sys; raise SystemExit(0 if sys.version_info >= (3, 6) else 1)' \\
      || die "Python 3.6+ required"
    log "Python OK"
    return
  fi
  log "installing Python 3..."
  case "$PKG_MGR" in
    apt) apt-get update -y && apt-get install -y python3 python3-pip ;;
    yum) yum install -y python3 python3-pip ;;
    dnf) dnf install -y python3 python3-pip ;;
    *) die "install Python 3.6+ manually" ;;
  esac
}}

ensure_ipmitool() {{
  if command -v ipmitool >/dev/null 2>&1; then log "ipmitool OK"; return; fi
  log "installing ipmitool..."
  case "$PKG_MGR" in
    apt) apt-get update -y && apt-get install -y ipmitool ;;
    yum) yum install -y OpenIPMI ipmitool ;;
    dnf) dnf install -y OpenIPMI ipmitool ;;
    *) die "install ipmitool manually" ;;
  esac
}}

ensure_requests() {{
  if python3 -c "import requests" >/dev/null 2>&1; then log "requests OK"; return; fi
  log "installing requests..."
  if command -v pip3 >/dev/null 2>&1; then
    pip3 install --upgrade requests
  else
    case "$PKG_MGR" in
      apt) apt-get install -y python3-pip && pip3 install --upgrade requests ;;
      yum) yum install -y python3-pip && pip3 install --upgrade requests ;;
      dnf) dnf install -y python3-pip && pip3 install --upgrade requests ;;
      *) die "install python3-requests manually" ;;
    esac
  fi
  python3 -c "import requests" || die "requests import failed"
}}

ensure_python
ensure_ipmitool
ensure_requests

if ! command -v dmidecode >/dev/null 2>&1; then
  case "$PKG_MGR" in
    apt) apt-get install -y dmidecode || true ;;
    yum) yum install -y dmidecode || true ;;
    dnf) dnf install -y dmidecode || true ;;
  esac
fi

mkdir -p "$AGENT_DIR" "$LOG_DIR"
chmod 755 "$AGENT_DIR" "$LOG_DIR"
cp -f "$TMP_COLLECTOR" "$COLLECTOR_DST"
chmod 755 "$COLLECTOR_DST"
rm -f "$TMP_COLLECTOR"

python3 -c "
from pathlib import Path
p = Path('${{COLLECTOR_DST}}')
sid = '''${{SERVER_ID}}'''
center = '''${{CENTER_URL}}'''
lines = []
for line in p.read_text(encoding='utf-8').splitlines(True):
    if line.startswith('SERVER_ID = '):
        lines.append('SERVER_ID = %r\\n' % sid)
    elif line.startswith('CENTER_URL = '):
        lines.append('CENTER_URL = %r\\n' % center)
    else:
        lines.append(line)
p.write_text(''.join(lines), encoding='utf-8')
"

grep -F "SERVER_ID = " "$COLLECTOR_DST" | head -1
grep -F "CENTER_URL = " "$COLLECTOR_DST" | head -1
python3 -c "import pathlib; t=pathlib.Path('${{COLLECTOR_DST}}').read_text(); assert 'SERVER_ID' in t and 'CENTER_URL' in t" \\
  || die "failed to inject config into collector.py"

cat > "$SERVICE_FILE" <<'EOF'
[Unit]
Description=FA Diagnosis Agent
After=network.target

[Service]
Type=simple
ExecStart=/usr/bin/python3 /opt/fa-agent/collector.py
Restart=on-failure
RestartSec=30
StandardOutput=append:/var/log/fa-agent/collector.log
StandardError=append:/var/log/fa-agent/collector.log

[Install]
WantedBy=multi-user.target
EOF

cat > "$TIMER_FILE" <<'EOF'
[Unit]
Description=FA Diagnosis Agent Timer

[Timer]
OnBootSec=1min
OnUnitActiveSec=5min
Unit=fa-collector.service

[Install]
WantedBy=timers.target
EOF

systemctl daemon-reload
systemctl enable fa-collector.timer
systemctl start fa-collector.timer
# Run once immediately so the center sees this host
systemctl start fa-collector.service || true

echo
echo "=============================================="
echo "  FA Diagnosis Agent installed"
echo "=============================================="
echo "  SERVER_ID : ${{SERVER_ID}}"
echo "  CENTER    : ${{CENTER_URL}}"
echo "  Logs      : ${{LOG_DIR}}/collector.log"
echo
echo "  systemctl status fa-collector.timer"
echo "  journalctl -u fa-collector.service -n 30 --no-pager"
echo "=============================================="
"""


@router.get("/collector.py")
def download_collector():
    if not _COLLECTOR_PATH.is_file():
        raise HTTPException(status_code=404, detail="collector.py not found on center")
    return FileResponse(
        path=_COLLECTOR_PATH,
        media_type="text/x-python",
        filename="collector.py",
    )


@router.get("/install.sh")
def one_click_install(
    request: Request,
    server_id: str = Query("Node-01", min_length=1, max_length=64),
):
    """Return a self-contained installer with center URL baked in."""
    if not _SERVER_ID_RE.match(server_id):
        raise HTTPException(
            status_code=400,
            detail="server_id must be alphanumeric (plus . _ -), max 64 chars",
        )
    base = _public_base(request)
    script = _build_install_script(base, server_id)
    return PlainTextResponse(
        content=script,
        media_type="text/x-shellscript",
        headers={
            "Content-Disposition": 'inline; filename="fa-agent-install.sh"',
        },
    )


_UNINSTALL_SCRIPT = """#!/bin/bash
# FA Diagnosis Agent — one-click uninstall
# Usage: curl -fsSL http://CENTER:8000/api/agent/uninstall.sh | sudo bash
set -euo pipefail

AGENT_DIR="/opt/fa-agent"
LOG_DIR="/var/log/fa-agent"
SERVICE_FILE="/etc/systemd/system/fa-collector.service"
TIMER_FILE="/etc/systemd/system/fa-collector.timer"

log() { echo "[fa-agent-uninstall] $*"; }
die() { echo "[fa-agent-uninstall] ERROR: $*" >&2; exit 1; }

[[ "$(id -u)" -eq 0 ]] || die "please run as root (sudo)"

if command -v systemctl >/dev/null 2>&1; then
  systemctl stop fa-collector.timer 2>/dev/null || true
  systemctl stop fa-collector.service 2>/dev/null || true
  systemctl disable fa-collector.timer 2>/dev/null || true
  systemctl disable fa-collector.service 2>/dev/null || true
  rm -f "$TIMER_FILE" "$SERVICE_FILE"
  systemctl daemon-reload 2>/dev/null || true
  systemctl reset-failed fa-collector.service 2>/dev/null || true
  systemctl reset-failed fa-collector.timer 2>/dev/null || true
  log "systemd units removed"
else
  log "systemctl not found; skipped unit cleanup"
fi

rm -rf "$AGENT_DIR"
log "removed ${AGENT_DIR}"

# Keep logs by default; set FA_PURGE_LOGS=1 to delete
if [[ "${FA_PURGE_LOGS:-0}" == "1" ]]; then
  rm -rf "$LOG_DIR"
  log "removed ${LOG_DIR}"
else
  log "kept ${LOG_DIR} (set FA_PURGE_LOGS=1 to purge)"
fi

echo
echo "=============================================="
echo "  FA Diagnosis Agent uninstalled"
echo "=============================================="
echo "  Note: center inventory is NOT cleared."
echo "  Remove the host in the FA UI if needed."
echo "=============================================="
"""


@router.get("/uninstall.sh")
def one_click_uninstall():
    """Return a self-contained agent uninstall script."""
    return PlainTextResponse(
        content=_UNINSTALL_SCRIPT,
        media_type="text/x-shellscript",
        headers={
            "Content-Disposition": 'inline; filename="fa-agent-uninstall.sh"',
        },
    )
